/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Alibaba Group
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


/**
 * FlutterBoostAbilityLaunchConfigs 类是用于配置FlutterBoostAbility启动的类。
 */
export default class FlutterBoostAbilityLaunchConfigs {
  // Intent extra arguments.
  // public static  EXTRA_BACKGROUND_MODE:String = "background_mode";
  // public static  EXTRA_CACHED_ENGINE_ID:String = "cached_engine_id";
  // public static  EXTRA_DESTROY_ENGINE_WITH_ACTIVITY:String = "destroy_engine_with_activity";
  // public static  EXTRA_ENABLE_STATE_RESTORATION:String = "enable_state_restoration";
  // public static  EXTRA_URL:String = "url";
  // public static  EXTRA_URL_PARAM:String = "url_param";
  public static EXTRA_UNIQUE_ID: string = "unique_id";
  // for onActivityResult
  // public static final String ACTIVITY_RESULT_KEY = "ActivityResult";

  // private FlutterActivityLaunchConfigs() {}
}
